WIP: use buildbotURLAliases to cover different hostnames.
buildbot/buildbot pull request #2615
Opened 2017-01-17 02:33 UTC by ewongbb

a possible wip to allow different aliases for the host.

2017-01-17 14:28 UTC, tardyp commented on www/base/src/app/home/home.tpl.jade
> +  .row(ng-if="config.buildbotURL != baseurl and config.buildbotURLAliases.indexof(baseurl) === -1")
I think we can have the buildbotURLAliases include the buildbotURL so that this expression is simplified

2017-01-18 09:25 UTC, tardyp requested changes
I think it would be useful to have the Aliases defaults to  "http://localhost:{}".format(self.www.get('port', 8010))

also, the default buildbotURL should be :8010 and not :8080 like I see  there

2017-01-18 09:25 UTC, tardyp commented on master/buildbot/status/master.py
> +    def getBuildbotURLAliases(self):
Please add unit tests for this function.

list.append() does not return the list

2017-01-21 04:00 UTC, ewongbb commented on master/buildbot/status/master.py
> +    def getBuildbotURLAliases(self):
so I need to change https://github.com/buildbot/buildbot/blob/master/master/buildbot/config.py#L194 to :8010?

2017-02-16 08:44 UTC, tardyp commented on master/buildbot/status/master.py
> +    def getBuildbotURLAliases(self):
Yes, I think that was a mistake

2017-02-16 08:45 UTC, tardyp commented
@ewongbb looks like we forgot this PR. There are some lint checks to fix, and very few comments to address, and then we can merge

2017-02-17 02:45 UTC, ewongbb commented
@tardyp re: 8080->8010..  with all those mentions of 8080 in the tests, am I doing something wrong?

2017-06-30 11:24 UTC, closed without merging

2026-09-05 15:59 UTC, andrewdicosmo commented on master/buildbot/status/master.py
> +    def getBuildbotURLAliases(self):
Addressed in 1abe424c. Tenant discovery now requires the pending recipient tenant to match its broadcast tenant. The new collision regression verifies no tenant is enqueued from another tenant's recipient row.