fix github status breaking on Nightly scheduler sourcestamps
buildbot/buildbot pull request #5507
Opened 2020-08-29 02:48 UTC by terencehonles

The Nightly scheduler will create sourcestamps with mostly None values, and this change will handle None better.

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

2020-08-29 14:36 UTC, tardyp requested changes
change looks good. We require unit test to be updated for each change of code to make sure the code coverage is good, and the code is well tested. thanks for understanding

2020-08-30 00:41 UTC, terencehonles commented
> change looks good. We require unit test to be updated for each change of code to make sure the code coverage is good, and the code is well tested. thanks for understanding

Done, I was mainly trying to trigger the CI since I didn't have tests running locally. I think it might be worthwhile to refactor the tests into a set of known scenarios and and then try them across all the reporters rather than having each reporter have its own tests for the scenarios that are added in an ad hoc manner.

I don't have time to do that right now, but It might be a good thing to try to track.

2020-08-30 12:25 UTC, p12tic commented
> I think it might be worthwhile to refactor the tests into a set of known scenarios and and then try them across all the reporters rather than having each reporter have its own tests for the scenarios that are added in an ad hoc manner.

Agreed

2020-08-30 12:26 UTC, p12tic approved these changes

2020-08-30 12:26 UTC, merged