fix renderable issue when using P4 streamwq
buildbot/buildbot pull request #5578
Opened 2020-10-12 10:54 UTC by bschatt

Fixes this error when using a renderable for p4base or p4branch in stream mode.
> builtins.TypeError: argument of type '_Renderer' is not iterable

2020-10-12 12:55 UTC, p12tic requested changes
Looks good, but can we add tests? A newsfragment is probably also useful because this bug is very easy to trigger. Thanks!

2020-10-15 17:42 UTC, senyai commented
I think these checks should be done in `_createClientSpec` (`raise buildstep.BuildStepFailed()` in case of an error), because there's no reason to ignore IRenderable.

2020-10-26 17:09 UTC, bschatt commented
The same thing is done a few lines above. https://github.com/buildbot/buildbot/blob/a2dc9a66a9cb38efa5a13f8361733c97f8246e29/master/buildbot/steps/source/p4.py#L101

I believe the reason is that function check for errors at config time, not run time. The perforce command will fail if the path is incorrect anyway, right?

2020-11-01 16:01 UTC, p12tic approved these changes
LGTM. I've fixed a typo in a test name and added newsfragment.

2020-11-01 16:01 UTC, merged