Minimal error reporting for GitHubPullrequestPoller
buildbot/buildbot pull request #5607
Opened 2020-11-01 22:10 UTC by senyai

Possible fix for #4878

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

2020-11-02 12:00 UTC, p12tic requested changes
LGTM, thanks. Can we have a test for this?

2020-11-02 12:09 UTC, senyai commented
Will try to make it this weekend.

2020-11-24 12:22 UTC, p12tic approved these changes

2020-11-24 12:22 UTC, p12tic commented
I've formatted the code a little bit.

2020-11-24 12:23 UTC, merged