ForceScheduler gets Responsible Users from owner property
buildbot/buildbot pull request #5621
Opened 2020-11-14 21:32 UTC by slim-builder

Fix for issue #3476

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

2020-11-14 22:01 UTC, p12tic commented on www/base/src/app/builders/builds/build.controller.js
> +                            $scope.responsibles[name] = email;
Bad indentation?

2020-11-14 22:03 UTC, p12tic requested changes
LGTM, just please add a newsfragment.

See master/buildbot/newsfragments/README.txt

2020-11-14 23:20 UTC, slim-builder commented on www/base/src/app/builders/builds/build.controller.js
> +                            $scope.responsibles[name] = email;
Fixed it.  Thanks!

2020-11-15 19:20 UTC, p12tic approved these changes

2020-11-15 19:21 UTC, merged