Fix WorkerLock's maxCountForWorker when used with buildsteps
buildbot/buildbot pull request #6133
Opened 2021-07-07 13:19 UTC by slawek-es

There has been an issue where the Worker object, rather than just the
worker's name, has been passed to 'RealWorkerLock.getLockForWorker'
when the lock was acquired for a single build step. As a result, the
erroneous 'workername' value was not found in the 'maxCountForWorker'
dictionary, and so we fell back to the 'maxCount' value.

We fix this by passing the workername rather than the Worker object
from 'BuildStep.startStep' into 'getLockForWorker'.

## Contributor Checklist:

* [ ] I have updated the unit tests
* [X] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

2021-07-07 13:19 UTC, slawek-es commented
This fixes https://github.com/buildbot/buildbot/issues/6132

2021-07-07 13:54 UTC, p12tic requested changes
LGTM, thanks a lot.

We probably need tests. These are currently in master/buildbot/test/unit/process/test_buildstep.py, but I'm not sure how to reproduce the bug in the test environment.

I will get back once I have an idea.

2021-07-07 13:54 UTC, tardyp commented
I guess we need a test for this usecase to make sure that this feature will always be working

2021-07-30 11:24 UTC, p12tic approved these changes
LGTM. Thanks for submitting this PR and doing full investigation.

2021-07-30 11:25 UTC, p12tic commented
I've added tests and rebased. Turns out we actually didn't test whether any locking happened.

2021-07-30 12:16 UTC, merged