process/buildrequestdistributor: sort unclaimed br cache by requestid
buildbot/buildbot pull request #7157
Opened 2023-10-11 15:51 UTC by iomartin

When choosing the next buildrequest to build, we first look at their priority, then break ties by choosing the oldest ("submitted_at" field).

However, if multiple buildrequests were created at the same time, they will all have the same "submitted_at". This makes it unpredictable which will be selected.

To make it predictable, we can break ties using the buildrequestid instead. This preserves the property of choosing the oldest (as a br with a lower id will have a submitted_at <= then a br with a higher id).

## Contributor Checklist:

* [X] I have updated the unit tests
* [X] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [X] I have updated the appropriate documentation

2023-10-19 17:02 UTC, iomartin commented
Any feedback @p12tic?

I believe the errors are unrelated to my changes

2023-11-06 00:07 UTC, p12tic requested changes
Thanks for the PR. It looks good, but contains accidental changes to `master/docs/relnotes/index.rst` which should be reverted.

Please also rebase on latest master.

2023-11-06 17:36 UTC, iomartin commented
Ok so it seems that my changes are in fact responsible for the failed CI test as the other PR I just opend (#7208) didn't fail that test. I'm looking into it.

2023-11-06 20:02 UTC, iomartin commented
Oh nevermind. After running a couple more times, I noticed that it was failing on different tests every time, and now it eventually passed. They were timeout errors, so the machine running them was likely overloaded.

It should be good to merge if you are happy with the changes

2023-11-07 04:03 UTC, p12tic approved these changes

2023-11-07 04:03 UTC, merged