waterfall_view: builds are now clickable links to their build page
buildbot/buildbot pull request #7791
Opened 2024-07-12 00:06 UTC by jvivenot

Builds in waterfall view now directly link to their own page. 

## Contributor Checklist:

* I have not updated the unit tests. Nothing relevant
* I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* I have not updated the appropriate documentation. Nothing relevant

2024-07-12 12:39 UTC, p12tic commented on www/waterfall_view/src/views/WaterfallView/Visualizer.ts
> +  function link_impl(this: d3.BaseType, d: unknown) {
linkImpl

2024-07-12 12:40 UTC, p12tic requested changes
Looks good except for single nit.

2024-07-13 23:05 UTC, p12tic approved these changes
Fixed the nit myself and rebased on top of latest master.

2024-07-13 23:06 UTC, merged

2024-07-14 13:23 UTC, jvivenot commented
> Fixed the nit myself and rebased on top of latest master.

Sorry about not dealing with your comment myself, I didn't have access to my computer for a few days. Thanks !

2024-07-15 15:32 UTC, p12tic commented
It's a pity that codespaces can't push directly to PR branch. Then fixing style issues like this has similar effort compared to writing a comment.