data: stream log lines to avoid loading the whole file in memory
buildbot/buildbot pull request #7865
Opened 2024-07-30 17:28 UTC by tdesveaux

Relates to #3011

We have some builders that generated huge logs (10+Go) due to an issue. Trying to download this log crashed the master with OOM.
This fixes the issue by streaming the log content to the HTTP response with an `AsyncGenerator`.

TODO:
- Need to find a way to not break the logchunk data API. Done ATM with the ugly `__accept_chunked_data` in kwargs.

Opening this, but will leave as WIP until I fix this. I'm open to suggestion.

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

2024-08-01 12:26 UTC, p12tic requested changes
Looks good overall. Marking as "request changes" until we figure out how to return async generators in data API.

2024-08-01 12:51 UTC, p12tic approved these changes
After thinking more, I think that this PR is good as is.

The out of memory behavior is a problem in the data API itself. This will require an API break of sorts.

However, we can still add a special internal API that only Buildbot uses which would fix web access. This would resolve 90% of the problem.

We can leave API upgrade for the future.

2024-08-01 19:14 UTC, p12tic commented on master/docs/developer/data.rst
> +            Note that the `raw` field can be an AsyncGeneratorType which yield chunks of data.
Let's not mention this until we have proper support for the feature.

2024-08-02 07:37 UTC, tdesveaux commented
@p12tic what do you think of introducing a `stream` method to endpoint? [really WIP stab at it](https://github.com/buildbot/buildbot/pull/7865/commits/a2ce5b444ad92367bab65ae426272f79d460a0be).

This would avoid breaking the get API and avoid to deal with awkward `raw` field being either a str or a generator.

Or do you consider the large ram usage of get a bug in any cases?

2024-08-02 08:26 UTC, p12tic commented
> what do you think of introducing a stream method to endpoint? [really WIP stab at it](https://github.com/buildbot/buildbot/pull/7865/commits/a2ce5b444ad92367bab65ae426272f79d460a0be).

This looks better indeed.

2024-08-02 15:07 UTC, tdesveaux commented
@p12tic  so some changes from the first implementation.

Added a `stream` method to avoid breaking `get`.
  This is an undocumented method to `Endpoint` with a disclaimer discouraging using it.
  making it public accessible to all endpoints will be a pain since `SINGLE` would not make sense and `COLLECTION` can return either an `iterable` or a `ListResult`. On top of that, `ResultSpec` would need to be aware of it.

I did not add tests as LogChunks `get` use `stream` internally, so currently implemented tests should be enough?

2024-08-02 15:39 UTC, p12tic commented
Looks good, thanks. We need a release note and there are several typos in the commit messages.

2024-08-02 16:23 UTC, tdesveaux commented
> there are several typos in the commit messages.

Could only spot one. Let me know if I missed some others.

2024-08-02 17:21 UTC, merged

2024-08-02 17:21 UTC, p12tic commented
> Could only spot one. Let me know if I missed some others.

Looks like I confused myself.