www: fix ansi color reset in log view
buildbot/buildbot pull request #7996
Opened 2024-09-17 13:33 UTC by q66

If we just return cssClasses, we are returning the previous instance which may be filled with existing colors. That means a reset sequence `CSI_PREFIX[m`, which has zero ansi classes, will result in the previous class set being used, rather than resetting the colors. This is in contrast to `CSI_PREFIX[0m`, which correctly empties the class set.

That said, in full log view, the escaper still gives up after 500something lines and starts printing unescaped sequences, e.g. like https://build.chimera-linux.org/#/builders/2/builds/1148/steps/5/logs/pkg_main_glycin-loaders_1_1_1-r0 - this is issue https://github.com/buildbot/buildbot/issues/7852 and appears to be unrelated.

2024-09-17 13:38 UTC, q66 commented
There is also another separate issue and that is when a color is set overriding the previous color without performing an explicit reset, that is unhandled here (the previous color will be shown because it will take on both classes and the browser will take the first one)

2024-09-17 13:39 UTC, q66 commented
i think the fix for that would be to change

```
    for (let i of ansiClasses) {
      if ((i === '39') || (i === '0')) { // "color reset" code and "all attributes off" code
        cssClasses = {};
      } else {
        cssClasses[`ansi${i}`] = true;
      }
    }
```

to always only have a single color class at a time, rather than adding more of them?

2024-09-17 13:49 UTC, q66 commented
a naive way to address that is probably like

```
index a4896c52f..651a910f5 100644
--- a/www/base/src/util/AnsiEscapeCodes.tsx
+++ b/www/base/src/util/AnsiEscapeCodes.tsx
@@ -92,6 +92,17 @@ export function ansiSgrClassesToCss(ansiClasses: string[], cssClasses: {[key: st
       if ((i === '39') || (i === '0')) { // "color reset" code and "all attributes off" code
         cssClasses = {};
       } else {
+        // if we're setting ansi color, reset other color classes if we have them
+        let j = parseInt(i);
+        if (j >= 30 && j <= 37) {
+            for (j = 30; j <= 37; ++j) {
+                delete cssClasses[`ansi${i}`];
+            }
+        } else if (j >= 40 && j <= 47) {
+            for (j = 40; j <= 47; ++j) {
+                delete cssClasses[`ansi${i}`];
+            }
+        }
         cssClasses[`ansi${i}`] = true;
       }
     }
```

i don't really like it though? any ideas?

2024-09-25 16:06 UTC, p12tic requested changes
Looks good, thanks.

Could you add a comment saying something like this: "According to ECMA-48 standard empty parameter set is interpreted as zero, which is a color reset code"?

Also, a unit test is needed. Please check out www/base/src/util/AnsiEscapeCodes.test.tsx which contains tests for parseEscapeCodesToClasses().

2024-09-25 16:07 UTC, q66 commented
do you have any comments wrt the fix for the above issue that i did not include in the patch?

2024-09-26 01:23 UTC, p12tic commented
> do you have any comments wrt the fix for the above issue that i did not include in the patch?

Sorry for missing the question the first time.

I think the map can be replaced with the following object:

```
{
    fg: string | null; // current foreground class (one set via 38 code)
    bg: string | null; // current background class (one set via 48 code)
    simpleColor: string | null; // current simple color class (one set via 30..37 codes)
    classes: {[key: string]: boolean}; // the rest of classes
}
```

Then clearing colors would be quite simple and efficient. Also, this would fix support for 38 code clearing previous 48 code setting and vice-versa which made it impossible to set both background and foreground at the same time.

Do I miss anything?

2024-09-26 08:20 UTC, q66 commented
looks fine, i'm not very familiar with typescript though...

2024-09-28 12:05 UTC, p12tic commented
@q66 If you aren't planning to finish this PR then I think someone else could take over as it's pretty straightforward what needs to be done for someone well versed in typescript.

2024-11-03 13:28 UTC, p12tic commented
This PR has been merged as part of https://github.com/buildbot/buildbot/pull/8180. Thanks a lot for investigation and providing preliminary fix.

2024-11-03 13:28 UTC, closed without merging