db: appendLog/getLogLines compression outside DB thread
buildbot/buildbot pull request #8157
Opened 2024-10-23 18:04 UTC by tdesveaux

Follow #8140, same work, on remaining methods.

## Contributor Checklist:

* [n/a] I have updated the unit tests
* [x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

2024-10-26 21:16 UTC, p12tic commented on master/buildbot/test/unit/db/test_logs.py
> +        def _join_lines(lines: list[str]):
I think this should be a separate commit. I got confused that the behavior is being changed, where in fact it is not.

2024-10-26 21:16 UTC, p12tic requested changes
Thanks for the PR. It looks great, I just had a single nit.

2024-10-29 14:28 UTC, p12tic approved these changes

2024-10-29 14:28 UTC, merged

2024-10-30 17:13 UTC, tdesveaux commented
@p12tic FYI, deployed this on a master that sees a lot of jobs running at the same time with fairly large logs.

It resulted in a bottleneck on the main thread staying at 100% usage, so there is an issue with this.
I'll investigate this week, but in the mean time, this should not be released.